package com.farware.recipesaver.feature_recipe.presentation.ui.theme

import androidx.compose.ui.graphics.Color

//          blue -  this is a keeper
val md_theme_light_primary = Color(0xFF3a5ba9)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd9e2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF00184a)
val md_theme_light_secondary = Color(0xFF585e71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdde2fa)
val md_theme_light_onSecondaryContainer = Color(0xFF151b2c)
val md_theme_light_tertiary = Color(0xFF735571)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFfed6f9)
val md_theme_light_onTertiaryContainer = Color(0xFF2b122c)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefbff)
val md_theme_light_onBackground = Color(0xFF1b1b1e)
val md_theme_light_surface = Color(0xFFfefbff)
val md_theme_light_onSurface = Color(0xFF1b1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe2e2ec)
val md_theme_light_onSurfaceVariant = Color(0xFF44464e)
val md_theme_light_outline = Color(0xFF75767f)
val md_theme_light_inverseOnSurface = Color(0xFFf2f0f5)
val md_theme_light_inverseSurface = Color(0xFF303033)
val md_theme_light_inversePrimary = Color(0xFFb0c5ff)
val md_theme_light_shadow = Color(0xff000000)

val md_theme_dark_primary = Color(0xFFb0c5ff)
val md_theme_dark_onPrimary = Color(0xFF002b76)
val md_theme_dark_primaryContainer = Color(0xFF1e428f)
val md_theme_dark_onPrimaryContainer = Color(0xFFd9e2ff)
val md_theme_dark_secondary = Color(0xFFc1c6dd)
val md_theme_dark_onSecondary = Color(0xFF2a3042)
val md_theme_dark_secondaryContainer = Color(0xFF404659)
val md_theme_dark_onSecondaryContainer = Color(0xFFdde2fa)
val md_theme_dark_tertiary = Color(0xFFe1bbdd)
val md_theme_dark_onTertiary = Color(0xFF422742)
val md_theme_dark_tertiaryContainer = Color(0xFF5a3d59)
val md_theme_dark_onTertiaryContainer = Color(0xFFfed6f9)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1e)
val md_theme_dark_onBackground = Color(0xFFe4e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1e)
val md_theme_dark_onSurface = Color(0xFFe4e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF44464e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc5c6d0)
val md_theme_dark_outline = Color(0xFF8f909a)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe4e2e6)
val md_theme_dark_inversePrimary = Color(0xFF3a5ba9)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFa7b3da)
val error = Color(0xFFba1b1b)

/*
// nice violet
val md_theme_light_primary = Color(0xFF5b53a7)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFe5deff)
val md_theme_light_onPrimaryContainer = Color(0xFF160362)
val md_theme_light_secondary = Color(0xFF5f5c71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe4dff9)
val md_theme_light_onSecondaryContainer = Color(0xFF1b192c)
val md_theme_light_tertiary = Color(0xFF7b5266)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd8e9)
val md_theme_light_onTertiaryContainer = Color(0xFF301122)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbff)
val md_theme_light_onBackground = Color(0xFF1c1b1f)
val md_theme_light_surface = Color(0xFFfffbff)
val md_theme_light_onSurface = Color(0xFF1c1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe5e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF47464e)
val md_theme_light_outline = Color(0xFF797680)
val md_theme_light_inverseOnSurface = Color(0xFFf4f0f4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFc7bfff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFc7bfff)
val md_theme_dark_onPrimary = Color(0xFF2d2277)
val md_theme_dark_primaryContainer = Color(0xFF433a8e)
val md_theme_dark_onPrimaryContainer = Color(0xFFe5deff)
val md_theme_dark_secondary = Color(0xFFc8c4dc)
val md_theme_dark_onSecondary = Color(0xFF302e42)
val md_theme_dark_secondaryContainer = Color(0xFF474559)
val md_theme_dark_onSecondaryContainer = Color(0xFFe4dff9)
val md_theme_dark_tertiary = Color(0xFFecb8cf)
val md_theme_dark_onTertiary = Color(0xFF482537)
val md_theme_dark_tertiaryContainer = Color(0xFF613b4e)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd8e9)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1c1b1f)
val md_theme_dark_onBackground = Color(0xFFe5e1e6)
val md_theme_dark_surface = Color(0xFF1c1b1f)
val md_theme_dark_onSurface = Color(0xFFe5e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF47464e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc9c5d0)
val md_theme_dark_outline = Color(0xFF928f9a)
val md_theme_dark_inverseOnSurface = Color(0xFF1c1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe5e1e6)
val md_theme_dark_inversePrimary = Color(0xFF5b53a7)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF928dbd)
val error = Color(0xFFba1b1b)
*/

/*
//          blue -  this is a keeper
val md_theme_light_primary = Color(0xFF3a5ba9)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd9e2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF00184a)
val md_theme_light_secondary = Color(0xFF585e71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdde2fa)
val md_theme_light_onSecondaryContainer = Color(0xFF151b2c)
val md_theme_light_tertiary = Color(0xFF735571)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFfed6f9)
val md_theme_light_onTertiaryContainer = Color(0xFF2b122c)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefbff)
val md_theme_light_onBackground = Color(0xFF1b1b1e)
val md_theme_light_surface = Color(0xFFfefbff)
val md_theme_light_onSurface = Color(0xFF1b1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe2e2ec)
val md_theme_light_onSurfaceVariant = Color(0xFF44464e)
val md_theme_light_outline = Color(0xFF75767f)
val md_theme_light_inverseOnSurface = Color(0xFFf2f0f5)
val md_theme_light_inverseSurface = Color(0xFF303033)
val md_theme_light_inversePrimary = Color(0xFFb0c5ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFb0c5ff)
val md_theme_dark_onPrimary = Color(0xFF002b76)
val md_theme_dark_primaryContainer = Color(0xFF1e428f)
val md_theme_dark_onPrimaryContainer = Color(0xFFd9e2ff)
val md_theme_dark_secondary = Color(0xFFc1c6dd)
val md_theme_dark_onSecondary = Color(0xFF2a3042)
val md_theme_dark_secondaryContainer = Color(0xFF404659)
val md_theme_dark_onSecondaryContainer = Color(0xFFdde2fa)
val md_theme_dark_tertiary = Color(0xFFe1bbdd)
val md_theme_dark_onTertiary = Color(0xFF422742)
val md_theme_dark_tertiaryContainer = Color(0xFF5a3d59)
val md_theme_dark_onTertiaryContainer = Color(0xFFfed6f9)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1e)
val md_theme_dark_onBackground = Color(0xFFe4e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1e)
val md_theme_dark_onSurface = Color(0xFFe4e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF44464e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc5c6d0)
val md_theme_dark_outline = Color(0xFF8f909a)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe4e2e6)
val md_theme_dark_inversePrimary = Color(0xFF3a5ba9)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFFa7b3da)
val error = Color(0xFFba1b1b)
*/

/*
// nice slate blue
val md_theme_light_primary = Color(0xFF00639a)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFcbe5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d32)
val md_theme_light_secondary = Color(0xFF51606f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd5e4f6)
val md_theme_light_onSecondaryContainer = Color(0xFF0e1d2a)
val md_theme_light_tertiary = Color(0xFF67587a)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFeedbff)
val md_theme_light_onTertiaryContainer = Color(0xFF221533)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcff)
val md_theme_light_onBackground = Color(0xFF1a1c1e)
val md_theme_light_surface = Color(0xFFfcfcff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFdee3eb)
val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val md_theme_light_outline = Color(0xFF72777e)
val md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
val md_theme_light_inverseSurface = Color(0xFF2f3032)
val md_theme_light_inversePrimary = Color(0xFF91ccff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF91ccff)
val md_theme_dark_onPrimary = Color(0xFF003353)
val md_theme_dark_primaryContainer = Color(0xFF004a75)
val md_theme_dark_onPrimaryContainer = Color(0xFFcbe5ff)
val md_theme_dark_secondary = Color(0xFFb8c8da)
val md_theme_dark_onSecondary = Color(0xFF233240)
val md_theme_dark_secondaryContainer = Color(0xFF394857)
val md_theme_dark_onSecondaryContainer = Color(0xFFd5e4f6)
val md_theme_dark_tertiary = Color(0xFFd2bfe6)
val md_theme_dark_onTertiary = Color(0xFF382a4a)
val md_theme_dark_tertiaryContainer = Color(0xFF4f4161)
val md_theme_dark_onTertiaryContainer = Color(0xFFeedbff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1e)
val md_theme_dark_onBackground = Color(0xFFe2e2e5)
val md_theme_dark_surface = Color(0xFF1a1c1e)
val md_theme_dark_onSurface = Color(0xFFe2e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF41474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c7ce)
val md_theme_dark_outline = Color(0xFF8c9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e5)
val md_theme_dark_inversePrimary = Color(0xFF00639a)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF8eaac6)
val error = Color(0xFFba1b1b)
*/


/*
// ok pea green
val md_theme_light_primary = Color(0xFF536500)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd5ed7d)
val md_theme_light_onPrimaryContainer = Color(0xFF171e00)
val md_theme_light_secondary = Color(0xFF5c6146)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe1e6c4)
val md_theme_light_onSecondaryContainer = Color(0xFF191d08)
val md_theme_light_tertiary = Color(0xFF3a665d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbcece0)
val md_theme_light_onTertiaryContainer = Color(0xFF00201a)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefcf3)
val md_theme_light_onBackground = Color(0xFF1b1c17)
val md_theme_light_surface = Color(0xFFfefcf3)
val md_theme_light_onSurface = Color(0xFF1b1c17)
val md_theme_light_surfaceVariant = Color(0xFFe3e3d3)
val md_theme_light_onSurfaceVariant = Color(0xFF46483b)
val md_theme_light_outline = Color(0xFF77786b)
val md_theme_light_inverseOnSurface = Color(0xFFf3f1e8)
val md_theme_light_inverseSurface = Color(0xFF31312c)
val md_theme_light_inversePrimary = Color(0xFFbad165)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFbad165)
val md_theme_dark_onPrimary = Color(0xFF293500)
val md_theme_dark_primaryContainer = Color(0xFF3d4d00)
val md_theme_dark_onPrimaryContainer = Color(0xFFd5ed7d)
val md_theme_dark_secondary = Color(0xFFc5caa9)
val md_theme_dark_onSecondary = Color(0xFF2e331b)
val md_theme_dark_secondaryContainer = Color(0xFF444930)
val md_theme_dark_onSecondaryContainer = Color(0xFFe1e6c4)
val md_theme_dark_tertiary = Color(0xFFa1d0c5)
val md_theme_dark_onTertiary = Color(0xFF03372f)
val md_theme_dark_tertiaryContainer = Color(0xFF214e46)
val md_theme_dark_onTertiaryContainer = Color(0xFFbcece0)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1c17)
val md_theme_dark_onBackground = Color(0xFFe5e3db)
val md_theme_dark_surface = Color(0xFF1b1c17)
val md_theme_dark_onSurface = Color(0xFFe5e3db)
val md_theme_dark_surfaceVariant = Color(0xFF46483b)
val md_theme_dark_onSurfaceVariant = Color(0xFFc7c8b8)
val md_theme_dark_outline = Color(0xFF909283)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1c17)
val md_theme_dark_inverseSurface = Color(0xFFe5e3db)
val md_theme_dark_inversePrimary = Color(0xFF536500)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF536500)
val error = Color(0xFFba1b1b)
 */

/*
// nice green
val md_theme_light_primary = Color(0xFF006c51)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF83f8cf)
val md_theme_light_onPrimaryContainer = Color(0xFF002116)
val md_theme_light_secondary = Color(0xFF4c6359)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcee8db)
val md_theme_light_onSecondaryContainer = Color(0xFF082018)
val md_theme_light_tertiary = Color(0xFF3f6375)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc3e8fe)
val md_theme_light_onTertiaryContainer = Color(0xFF001e2b)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfafdf9)
val md_theme_light_onBackground = Color(0xFF191c1b)
val md_theme_light_surface = Color(0xFFfafdf9)
val md_theme_light_onSurface = Color(0xFF191c1b)
val md_theme_light_surfaceVariant = Color(0xFFdbe5de)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4944)
val md_theme_light_outline = Color(0xFF707974)
val md_theme_light_inverseOnSurface = Color(0xFFeff2ee)
val md_theme_light_inverseSurface = Color(0xFF2e312f)
val md_theme_light_inversePrimary = Color(0xFF65dbb4)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF65dbb4)
val md_theme_dark_onPrimary = Color(0xFF003828)
val md_theme_dark_primaryContainer = Color(0xFF00513c)
val md_theme_dark_onPrimaryContainer = Color(0xFF83f8cf)
val md_theme_dark_secondary = Color(0xFFb3ccc0)
val md_theme_dark_onSecondary = Color(0xFF1e352c)
val md_theme_dark_secondaryContainer = Color(0xFF344c42)
val md_theme_dark_onSecondaryContainer = Color(0xFFcee8db)
val md_theme_dark_tertiary = Color(0xFFa7cce1)
val md_theme_dark_onTertiary = Color(0xFF0b3445)
val md_theme_dark_tertiaryContainer = Color(0xFF264b5d)
val md_theme_dark_onTertiaryContainer = Color(0xFFc3e8fe)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1b)
val md_theme_dark_onBackground = Color(0xFFe1e3e0)
val md_theme_dark_surface = Color(0xFF191c1b)
val md_theme_dark_onSurface = Color(0xFFe1e3e0)
val md_theme_dark_surfaceVariant = Color(0xFF3f4944)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc9c3)
val md_theme_dark_outline = Color(0xFF8a938e)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1b)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e0)
val md_theme_dark_inversePrimary = Color(0xFF006c51)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF356f5b)
val error = Color(0xFFba1b1b)
 */

